name: sos_central
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.3.3
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  iconly: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/raster/

  uses-material-design: true
  fonts:
    - family: Dm_sans
      fonts:
        - asset: assets/fonts/DMSans.ttf